# Generated by Django 5.1.1 on 2024-09-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetaryPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet', models.CharField(max_length=2)),
                ('zodiac_sign', models.CharField(max_length=2)),
                ('retrograde', models.BooleanField(default=False)),
                ('date', models.DateField()),
            ],
        ),
    ]
